import { SHARED_LIMITS } from "@sitecue/shared";

export const APP_LIMITS = {
	MAX_NOTE_LENGTH: SHARED_LIMITS.MAX_NOTE_LENGTH,
	MAX_DRAFT_LENGTH: SHARED_LIMITS.MAX_DRAFT_LENGTH,
	MAX_TEMPLATE_LENGTH: SHARED_LIMITS.MAX_TEMPLATE_LENGTH,
} as const;
